# Generated by Django 4.2.20 on 2025-04-22 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('post', 'Post'), ('comment', 'Comment'), ('story', 'Story'), ('reel', 'Reel'), ('message', 'Message'), ('user', 'User Profile')], max_length=10)),
                ('content_id', models.CharField(max_length=100)),
                ('report_type', models.CharField(choices=[('spam', 'Spam'), ('nudity', 'Nudity or sexual activity'), ('hate_speech', 'Hate speech or symbols'), ('violence', 'Violence or dangerous organizations'), ('illegal', 'Sale of illegal goods'), ('bullying', 'Bullying or harassment'), ('intellectual_property', 'Intellectual property violation'), ('suicide', 'Suicide or self-injury'), ('eating_disorders', 'Eating disorders'), ('scam', 'Scam or fraud'), ('false_information', 'False information'), ('other', 'Other')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_reviewed', models.BooleanField(default=False)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('action_taken', models.CharField(blank=True, max_length=255)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('bug', 'Bug Report'), ('feature', 'Feature Request'), ('content', 'Content Issue'), ('account', 'Account Issue'), ('other', 'Other')], max_length=10)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='uploads/feedback/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('response', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('post_create', 'Create Post'), ('post_view', 'View Post'), ('post_like', 'Like Post'), ('post_comment', 'Comment on Post'), ('post_share', 'Share Post'), ('story_create', 'Create Story'), ('story_view', 'View Story'), ('reel_create', 'Create Reel'), ('reel_view', 'View Reel'), ('profile_view', 'View Profile'), ('follow', 'Follow User'), ('unfollow', 'Unfollow User'), ('message_send', 'Send Message'), ('search', 'Search'), ('notification_click', 'Click Notification')], max_length=20)),
                ('content_id', models.CharField(blank=True, max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Activities',
                'ordering': ['-created_at'],
            },
        ),
    ]
