# Generated by Django 4.2.20 on 2025-04-22 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes', models.BooleanField(default=True)),
                ('comments', models.BooleanField(default=True)),
                ('comment_likes', models.BooleanField(default=True)),
                ('follows', models.BooleanField(default=True)),
                ('follow_requests', models.BooleanField(default=True)),
                ('messages', models.BooleanField(default=True)),
                ('mentions', models.BooleanField(default=True)),
                ('tags', models.BooleanField(default=True)),
                ('story_views', models.BooleanField(default=False)),
                ('story_reactions', models.BooleanField(default=True)),
                ('post_shares', models.BooleanField(default=True)),
                ('email_likes', models.BooleanField(default=False)),
                ('email_comments', models.BooleanField(default=False)),
                ('email_follows', models.BooleanField(default=True)),
                ('email_messages', models.BooleanField(default=False)),
                ('email_system', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('like', 'Like'), ('comment', 'Comment'), ('follow', 'Follow'), ('mention', 'Mention'), ('tag', 'Tag'), ('message', 'Message'), ('comment_like', 'Comment Like'), ('follow_request', 'Follow Request'), ('story_view', 'Story View'), ('story_reaction', 'Story Reaction'), ('post_share', 'Post Share'), ('reel_like', 'Reel Like'), ('reel_comment', 'Reel Comment'), ('system', 'System Notification')], max_length=20)),
                ('content_id', models.CharField(blank=True, max_length=100)),
                ('text', models.TextField(blank=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
